package it.univaq.disim.bpd;

import java.util.HashMap;
import java.util.Map;

import org.camunda.bpm.engine.MismatchingMessageCorrelationException;
import org.camunda.bpm.engine.RuntimeService;
import org.camunda.bpm.engine.runtime.ProcessInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api")
public class ProcessController {

    @Autowired
    private RuntimeService runtimeService;

    // Request Availability API
    @PostMapping("/request")
    public ResponseEntity<?> requestAvailability(@RequestBody AvailabilityRequestDto input) {
        
        // input validation
        if (input.getUsername() == null || input.getUsername().isEmpty() || 
            input.getCities() == null || input.getCities().isEmpty()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(Map.of("error", "Missing data: username and cities are mandatory."));
        }

        try {
            // prepare variables for camunda
            Map<String, Object> variables = new HashMap<>();
            variables.put("username", input.getUsername());
            variables.put("posterFormat", input.getPosterFormat());
            // cities is a map: e.g. {"Rome": 50.0, "Milan": 80.0}
            variables.put("cities", input.getCities()); 

            // start the process
            ProcessInstance instance = runtimeService.startProcessInstanceByKey("PosterCamundaProcess", variables);

            // retrieve the variables generated by the process (e.g. requestId and zones)
            // NOTE: focus on the Intermediate Catch Message Event, may not work otherwise
            Map<String, Object> responseData = new HashMap<>();
            
            // Extract the variables that the process (or service tasks) should have created
            Object requestId = runtimeService.getVariable(instance.getId(), "requestId");
            Object selectedZones = runtimeService.getVariable(instance.getId(), "selectedZones");
            Object totalPrice = runtimeService.getVariable(instance.getId(), "totalPrice");

            responseData.put("message", "Request successfully accepted.");
            responseData.put("processInstanceId", instance.getId());
            responseData.put("requestId", requestId);
            responseData.put("selectedZones", selectedZones);
            responseData.put("totalPrice", totalPrice);

            return ResponseEntity.ok(responseData);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Error during process start: " + e.getMessage()));
        }
    }

    // Send Decision API
    @PostMapping("/decision")
    public ResponseEntity<?> sendDecision(@RequestBody DecisionRequestDto input) {
        
        // input validation
        if (input.getRequestId() == null || input.getRequestId().isEmpty()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(Map.of("error", "requestId is mandatory."));
        }

        String decision = input.getDecision();
        if (!"confirm".equalsIgnoreCase(decision) && !"cancel".equalsIgnoreCase(decision)) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(Map.of("error", "decision must be 'confirm' or 'cancel'."));
        }

        try {
            // wake up the waiting process based on requestId
            // in the camunda modeler, message event MUST have the name "DecisionMessage"
            runtimeService.createMessageCorrelation("DecisionMessage")
                    .processInstanceVariableEquals("requestId", input.getRequestId())
                    .setVariable("decision", decision.toLowerCase())
                    .correlate();

            return ResponseEntity.ok(Map.of("message", "Decision successfully processed for request: " + input.getRequestId()));

        } catch (MismatchingMessageCorrelationException e) {
            // if the user sends a non-existent or already processed requestId
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(Map.of("error", "No waiting process instance found for requestId: " + input.getRequestId()));
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "System error: " + e.getMessage()));
        }
    }


    // DTOs

    public static class AvailabilityRequestDto {
        private String username;
        private String posterFormat;
        private Map<String, Double> cities; // key: city name, value: maximum budget

        // getters and setters
        public String getUsername() { return username; }
        public void setUsername(String username) { this.username = username; }

        public String getPosterFormat() { return posterFormat; }
        public void setPosterFormat(String posterFormat) { this.posterFormat = posterFormat; }

        public Map<String, Double> getCities() { return cities; }
        public void setCities(Map<String, Double> cities) { this.cities = cities; }
    }

    public static class DecisionRequestDto {
        private String requestId;
        private String decision;

        // getters and setters
        public String getRequestId() { return requestId; }
        public void setRequestId(String requestId) { this.requestId = requestId; }

        public String getDecision() { return decision; }
        public void setDecision(String decision) { this.decision = decision; }
    }
}