server.port=8080

app.selection.default-strategy=most-expensive-first
app.output-file=posting_requests.txt

app.services.user-base-url=http://localhost:9080
app.services.zones-base-url=http://localhost:9090
app.services.posting-soap-url=http://localhost:8888/ws

app.camunda.messages.availability-request=availability-request-message
app.camunda.messages.decision=decision-received-message

spring.datasource.url=jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

camunda.bpm.database.schema-update=true
camunda.bpm.auto-deployment-enabled=true
camunda.bpm.history-level=full
